name: Empty Commit

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:        # also allows manual triggering

permissions:
  contents: write

jobs:
  empty_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Make and push empty commit
        run: |
          git commit --allow-empty -m "Keep alive commit"
          git push
